#ifndef TICKC_X86_64_CODEGEN_H
#define TICKC_X86_64_CODEGEN_H

/* Hardware register numbers are their ModRM encodings. */
#define __RAX 0
#define __RCX 1
#define __RDX 2
#define __RBX 3
#define __RSP 4
#define __RBP 5
#define __RSI 6
#define __RDI 7
#define __R8 8
#define __R9 9
#define __R10 10
#define __R11 11
#define __R12 12
#define __R13 13
#define __R14 14
#define __R15 15
#define __XMM0 16
#define __XMM1 17
#define __XMM2 18
#define __XMM3 19
#define __XMM4 20
#define __XMM5 21
#define __XMM6 22
#define __XMM7 23
#define __XMM8 24
#define __XMM9 25
#define __XMM10 26
#define __XMM11 27
#define __XMM12 28
#define __XMM13 29
#define __XMM14 30
#define __XMM15 31

#define __VIRT(reg) ((reg) < 0)
#define __NVIRT(reg) ((reg) >= 0)
#define __REG(reg) (reg)
#define __ADDR(reg) (reg)
#define __MKVIRT(offset) (-(offset))
#define __MKNVIRT(reg) (reg)

#define v_lp __RBP
#define v_zero 0x7fffffff

#define V_X64_ADD 0
#define V_X64_SUB 1
#define V_X64_MUL 2
#define V_X64_DIV 3
#define V_X64_MOD 4
#define V_X64_AND 5
#define V_X64_OR 6
#define V_X64_XOR 7
#define V_X64_LSH 8
#define V_X64_RSH 9
#define V_X64_COM 0
#define V_X64_NOT 1
#define V_X64_NEG 2
#define V_X64_LT 0
#define V_X64_LE 1
#define V_X64_GT 2
#define V_X64_GE 3
#define V_X64_EQ 4
#define V_X64_NE 5

#define v_addi(d,a,b)   v_emit_binary(V_X64_ADD,V_I,d,a,b)
#define v_addu(d,a,b)   v_emit_binary(V_X64_ADD,V_U,d,a,b)
#define v_addl(d,a,b)   v_emit_binary(V_X64_ADD,V_L,d,a,b)
#define v_addul(d,a,b)  v_emit_binary(V_X64_ADD,V_UL,d,a,b)
#define v_addp(d,a,b)   v_emit_binary(V_X64_ADD,V_P,d,a,b)
#define v_addf(d,a,b)   v_emit_binary(V_X64_ADD,V_F,d,a,b)
#define v_addd(d,a,b)   v_emit_binary(V_X64_ADD,V_D,d,a,b)
#define v_addii(d,a,b)  v_emit_binary_imm(V_X64_ADD,V_I,d,a,(intptr_t)(b))
#define v_addui(d,a,b)  v_emit_binary_imm(V_X64_ADD,V_U,d,a,(intptr_t)(b))
#define v_addli(d,a,b)  v_emit_binary_imm(V_X64_ADD,V_L,d,a,(intptr_t)(b))
#define v_adduli(d,a,b) v_emit_binary_imm(V_X64_ADD,V_UL,d,a,(intptr_t)(b))
#define v_addpi(d,a,b)  v_emit_binary_imm(V_X64_ADD,V_P,d,a,(intptr_t)(b))

#define v_subi(d,a,b)   v_emit_binary(V_X64_SUB,V_I,d,a,b)
#define v_subu(d,a,b)   v_emit_binary(V_X64_SUB,V_U,d,a,b)
#define v_subl(d,a,b)   v_emit_binary(V_X64_SUB,V_L,d,a,b)
#define v_subul(d,a,b)  v_emit_binary(V_X64_SUB,V_UL,d,a,b)
#define v_subp(d,a,b)   v_emit_binary(V_X64_SUB,V_P,d,a,b)
#define v_subf(d,a,b)   v_emit_binary(V_X64_SUB,V_F,d,a,b)
#define v_subd(d,a,b)   v_emit_binary(V_X64_SUB,V_D,d,a,b)
#define v_subii(d,a,b)  v_emit_binary_imm(V_X64_SUB,V_I,d,a,(intptr_t)(b))
#define v_subui(d,a,b)  v_emit_binary_imm(V_X64_SUB,V_U,d,a,(intptr_t)(b))
#define v_subli(d,a,b)  v_emit_binary_imm(V_X64_SUB,V_L,d,a,(intptr_t)(b))
#define v_subuli(d,a,b) v_emit_binary_imm(V_X64_SUB,V_UL,d,a,(intptr_t)(b))
#define v_subpi(d,a,b)  v_emit_binary_imm(V_X64_SUB,V_P,d,a,(intptr_t)(b))

#define v_muli(d,a,b)   v_emit_binary(V_X64_MUL,V_I,d,a,b)
#define v_mulu(d,a,b)   v_emit_binary(V_X64_MUL,V_U,d,a,b)
#define v_mull(d,a,b)   v_emit_binary(V_X64_MUL,V_L,d,a,b)
#define v_mulul(d,a,b)  v_emit_binary(V_X64_MUL,V_UL,d,a,b)
#define v_mulf(d,a,b)   v_emit_binary(V_X64_MUL,V_F,d,a,b)
#define v_muld(d,a,b)   v_emit_binary(V_X64_MUL,V_D,d,a,b)
#define v_mulii(d,a,b)  v_emit_binary_imm(V_X64_MUL,V_I,d,a,(intptr_t)(b))
#define v_mului(d,a,b)  v_emit_binary_imm(V_X64_MUL,V_U,d,a,(intptr_t)(b))
#define v_mulli(d,a,b)  v_emit_binary_imm(V_X64_MUL,V_L,d,a,(intptr_t)(b))
#define v_mululi(d,a,b) v_emit_binary_imm(V_X64_MUL,V_UL,d,a,(intptr_t)(b))
#define v_cmull(d,a,b)  v_mulli(d,a,b)
#define v_cmulul(d,a,b) v_mululi(d,a,b)

#define v_divi(d,a,b)   v_emit_binary(V_X64_DIV,V_I,d,a,b)
#define v_divu(d,a,b)   v_emit_binary(V_X64_DIV,V_U,d,a,b)
#define v_divl(d,a,b)   v_emit_binary(V_X64_DIV,V_L,d,a,b)
#define v_divul(d,a,b)  v_emit_binary(V_X64_DIV,V_UL,d,a,b)
#define v_divf(d,a,b)   v_emit_binary(V_X64_DIV,V_F,d,a,b)
#define v_divd(d,a,b)   v_emit_binary(V_X64_DIV,V_D,d,a,b)
#define v_divii(d,a,b)  v_emit_binary_imm(V_X64_DIV,V_I,d,a,(intptr_t)(b))
#define v_divui(d,a,b)  v_emit_binary_imm(V_X64_DIV,V_U,d,a,(intptr_t)(b))
#define v_divli(d,a,b)  v_emit_binary_imm(V_X64_DIV,V_L,d,a,(intptr_t)(b))
#define v_divuli(d,a,b) v_emit_binary_imm(V_X64_DIV,V_UL,d,a,(intptr_t)(b))

#define v_modi(d,a,b)   v_emit_binary(V_X64_MOD,V_I,d,a,b)
#define v_modu(d,a,b)   v_emit_binary(V_X64_MOD,V_U,d,a,b)
#define v_modl(d,a,b)   v_emit_binary(V_X64_MOD,V_L,d,a,b)
#define v_modul(d,a,b)  v_emit_binary(V_X64_MOD,V_UL,d,a,b)
#define v_modii(d,a,b)  v_emit_binary_imm(V_X64_MOD,V_I,d,a,(intptr_t)(b))
#define v_modui(d,a,b)  v_emit_binary_imm(V_X64_MOD,V_U,d,a,(intptr_t)(b))
#define v_modli(d,a,b)  v_emit_binary_imm(V_X64_MOD,V_L,d,a,(intptr_t)(b))
#define v_moduli(d,a,b) v_emit_binary_imm(V_X64_MOD,V_UL,d,a,(intptr_t)(b))

#define v_andi(d,a,b)   v_emit_binary(V_X64_AND,V_I,d,a,b)
#define v_andu(d,a,b)   v_emit_binary(V_X64_AND,V_U,d,a,b)
#define v_andl(d,a,b)   v_emit_binary(V_X64_AND,V_L,d,a,b)
#define v_andul(d,a,b)  v_emit_binary(V_X64_AND,V_UL,d,a,b)
#define v_andii(d,a,b)  v_emit_binary_imm(V_X64_AND,V_I,d,a,(intptr_t)(b))
#define v_andui(d,a,b)  v_emit_binary_imm(V_X64_AND,V_U,d,a,(intptr_t)(b))
#define v_andli(d,a,b)  v_emit_binary_imm(V_X64_AND,V_L,d,a,(intptr_t)(b))
#define v_anduli(d,a,b) v_emit_binary_imm(V_X64_AND,V_UL,d,a,(intptr_t)(b))
#define v_ori(d,a,b)    v_emit_binary(V_X64_OR,V_I,d,a,b)
#define v_oru(d,a,b)    v_emit_binary(V_X64_OR,V_U,d,a,b)
#define v_orl(d,a,b)    v_emit_binary(V_X64_OR,V_L,d,a,b)
#define v_orul(d,a,b)   v_emit_binary(V_X64_OR,V_UL,d,a,b)
#define v_orii(d,a,b)   v_emit_binary_imm(V_X64_OR,V_I,d,a,(intptr_t)(b))
#define v_orui(d,a,b)   v_emit_binary_imm(V_X64_OR,V_U,d,a,(intptr_t)(b))
#define v_orli(d,a,b)   v_emit_binary_imm(V_X64_OR,V_L,d,a,(intptr_t)(b))
#define v_oruli(d,a,b)  v_emit_binary_imm(V_X64_OR,V_UL,d,a,(intptr_t)(b))
#define v_xori(d,a,b)   v_emit_binary(V_X64_XOR,V_I,d,a,b)
#define v_xoru(d,a,b)   v_emit_binary(V_X64_XOR,V_U,d,a,b)
#define v_xorl(d,a,b)   v_emit_binary(V_X64_XOR,V_L,d,a,b)
#define v_xorul(d,a,b)  v_emit_binary(V_X64_XOR,V_UL,d,a,b)
#define v_xorii(d,a,b)  v_emit_binary_imm(V_X64_XOR,V_I,d,a,(intptr_t)(b))
#define v_xorui(d,a,b)  v_emit_binary_imm(V_X64_XOR,V_U,d,a,(intptr_t)(b))
#define v_xorli(d,a,b)  v_emit_binary_imm(V_X64_XOR,V_L,d,a,(intptr_t)(b))
#define v_xoruli(d,a,b) v_emit_binary_imm(V_X64_XOR,V_UL,d,a,(intptr_t)(b))

#define v_lshi(d,a,b)   v_emit_binary(V_X64_LSH,V_I,d,a,b)
#define v_lshu(d,a,b)   v_emit_binary(V_X64_LSH,V_U,d,a,b)
#define v_lshl(d,a,b)   v_emit_binary(V_X64_LSH,V_L,d,a,b)
#define v_lshul(d,a,b)  v_emit_binary(V_X64_LSH,V_UL,d,a,b)
#define v_lshii(d,a,b)  v_emit_binary_imm(V_X64_LSH,V_I,d,a,(intptr_t)(b))
#define v_lshui(d,a,b)  v_emit_binary_imm(V_X64_LSH,V_U,d,a,(intptr_t)(b))
#define v_lshli(d,a,b)  v_emit_binary_imm(V_X64_LSH,V_L,d,a,(intptr_t)(b))
#define v_lshuli(d,a,b) v_emit_binary_imm(V_X64_LSH,V_UL,d,a,(intptr_t)(b))
#define v_rshi(d,a,b)   v_emit_binary(V_X64_RSH,V_I,d,a,b)
#define v_rshu(d,a,b)   v_emit_binary(V_X64_RSH,V_U,d,a,b)
#define v_rshl(d,a,b)   v_emit_binary(V_X64_RSH,V_L,d,a,b)
#define v_rshul(d,a,b)  v_emit_binary(V_X64_RSH,V_UL,d,a,b)
#define v_rshii(d,a,b)  v_emit_binary_imm(V_X64_RSH,V_I,d,a,(intptr_t)(b))
#define v_rshui(d,a,b)  v_emit_binary_imm(V_X64_RSH,V_U,d,a,(intptr_t)(b))
#define v_rshli(d,a,b)  v_emit_binary_imm(V_X64_RSH,V_L,d,a,(intptr_t)(b))
#define v_rshuli(d,a,b) v_emit_binary_imm(V_X64_RSH,V_UL,d,a,(intptr_t)(b))

#define v_movi(d,s)  v_emit_move(V_I,d,s)
#define v_movu(d,s)  v_emit_move(V_U,d,s)
#define v_movl(d,s)  v_emit_move(V_L,d,s)
#define v_movul(d,s) v_emit_move(V_UL,d,s)
#define v_movp(d,s)  v_emit_move(V_P,d,s)
#define v_movf(d,s)  v_emit_move(V_F,d,s)
#define v_movd(d,s)  v_emit_move(V_D,d,s)
#define v_setc(d,i)  v_emit_set(V_C,d,(uintptr_t)(intptr_t)(i))
#define v_setuc(d,i) v_emit_set(V_UC,d,(uintptr_t)(i))
#define v_sets(d,i)  v_emit_set(V_S,d,(uintptr_t)(intptr_t)(i))
#define v_setus(d,i) v_emit_set(V_US,d,(uintptr_t)(i))
#define v_seti(d,i)  v_emit_set(V_I,d,(uintptr_t)(intptr_t)(i))
#define v_setu(d,i)  v_emit_set(V_U,d,(uintptr_t)(i))
#define v_setl(d,i)  v_emit_set(V_L,d,(uintptr_t)(intptr_t)(i))
#define v_setul(d,i) v_emit_set(V_UL,d,(uintptr_t)(i))
#define v_setp(d,i)  v_emit_set(V_P,d,(uintptr_t)(i))
#define v_setv(d,i)  v_emit_set(V_P,d,(uintptr_t)(i))
#define v_setf(d,i)  v_emit_set_float(V_F,d,(double)(i))
#define v_setd(d,i)  v_emit_set_float(V_D,d,(double)(i))

#define v_comi(d,s)  v_emit_unary(V_X64_COM,V_I,d,s)
#define v_comu(d,s)  v_emit_unary(V_X64_COM,V_U,d,s)
#define v_coml(d,s)  v_emit_unary(V_X64_COM,V_L,d,s)
#define v_comul(d,s) v_emit_unary(V_X64_COM,V_UL,d,s)
#define v_comii(d,s) v_emit_set(V_I,d,(uintptr_t)~(uint32_t)(s))
#define v_comui(d,s) v_emit_set(V_U,d,(uintptr_t)~(uint32_t)(s))
#define v_comli(d,s) v_emit_set(V_L,d,(uintptr_t)~(uint64_t)(s))
#define v_comuli(d,s) v_emit_set(V_UL,d,(uintptr_t)~(uint64_t)(s))
#define v_noti(d,s)  v_emit_unary(V_X64_NOT,V_I,d,s)
#define v_notu(d,s)  v_emit_unary(V_X64_NOT,V_U,d,s)
#define v_notl(d,s)  v_emit_unary(V_X64_NOT,V_L,d,s)
#define v_notul(d,s) v_emit_unary(V_X64_NOT,V_UL,d,s)
#define v_notii(d,s) v_emit_set(V_I,d,!(s))
#define v_notui(d,s) v_emit_set(V_U,d,!(s))
#define v_notli(d,s) v_emit_set(V_L,d,!(s))
#define v_notuli(d,s) v_emit_set(V_UL,d,!(s))
#define v_negi(d,s)  v_emit_unary(V_X64_NEG,V_I,d,s)
#define v_negu(d,s)  v_emit_unary(V_X64_NEG,V_U,d,s)
#define v_negl(d,s)  v_emit_unary(V_X64_NEG,V_L,d,s)
#define v_negul(d,s) v_emit_unary(V_X64_NEG,V_UL,d,s)
#define v_negf(d,s)  v_emit_unary(V_X64_NEG,V_F,d,s)
#define v_negd(d,s)  v_emit_unary(V_X64_NEG,V_D,d,s)
#define v_negii(d,s) v_emit_set(V_I,d,(uintptr_t)(-(int32_t)(s)))
#define v_negui(d,s) v_emit_set(V_U,d,(uintptr_t)(-(uint32_t)(s)))
#define v_negli(d,s) v_emit_set(V_L,d,(uintptr_t)(-(int64_t)(s)))
#define v_neguli(d,s) v_emit_set(V_UL,d,(uintptr_t)(-(uint64_t)(s)))

#define v_blti(a,b,l)   v_emit_branch(V_X64_LT,V_I,a,b,1,l)
#define v_bltu(a,b,l)   v_emit_branch(V_X64_LT,V_U,a,b,1,l)
#define v_bltl(a,b,l)   v_emit_branch(V_X64_LT,V_L,a,b,1,l)
#define v_bltul(a,b,l)  v_emit_branch(V_X64_LT,V_UL,a,b,1,l)
#define v_bltp(a,b,l)   v_emit_branch(V_X64_LT,V_P,a,b,1,l)
#define v_bltii(a,b,l)  v_emit_branch(V_X64_LT,V_I,a,(intptr_t)(b),0,l)
#define v_bltui(a,b,l)  v_emit_branch(V_X64_LT,V_U,a,(intptr_t)(b),0,l)
#define v_bltli(a,b,l)  v_emit_branch(V_X64_LT,V_L,a,(intptr_t)(b),0,l)
#define v_bltuli(a,b,l) v_emit_branch(V_X64_LT,V_UL,a,(intptr_t)(b),0,l)
#define v_bltpi(a,b,l)  v_emit_branch(V_X64_LT,V_P,a,(intptr_t)(b),0,l)
#define v_blei(a,b,l)   v_emit_branch(V_X64_LE,V_I,a,b,1,l)
#define v_bleu(a,b,l)   v_emit_branch(V_X64_LE,V_U,a,b,1,l)
#define v_blel(a,b,l)   v_emit_branch(V_X64_LE,V_L,a,b,1,l)
#define v_bleul(a,b,l)  v_emit_branch(V_X64_LE,V_UL,a,b,1,l)
#define v_blep(a,b,l)   v_emit_branch(V_X64_LE,V_P,a,b,1,l)
#define v_bleii(a,b,l)  v_emit_branch(V_X64_LE,V_I,a,(intptr_t)(b),0,l)
#define v_bleui(a,b,l)  v_emit_branch(V_X64_LE,V_U,a,(intptr_t)(b),0,l)
#define v_bleli(a,b,l)  v_emit_branch(V_X64_LE,V_L,a,(intptr_t)(b),0,l)
#define v_bleuli(a,b,l) v_emit_branch(V_X64_LE,V_UL,a,(intptr_t)(b),0,l)
#define v_blepi(a,b,l)  v_emit_branch(V_X64_LE,V_P,a,(intptr_t)(b),0,l)
#define v_bgti(a,b,l)   v_emit_branch(V_X64_GT,V_I,a,b,1,l)
#define v_bgtu(a,b,l)   v_emit_branch(V_X64_GT,V_U,a,b,1,l)
#define v_bgtl(a,b,l)   v_emit_branch(V_X64_GT,V_L,a,b,1,l)
#define v_bgtul(a,b,l)  v_emit_branch(V_X64_GT,V_UL,a,b,1,l)
#define v_bgtp(a,b,l)   v_emit_branch(V_X64_GT,V_P,a,b,1,l)
#define v_bgtii(a,b,l)  v_emit_branch(V_X64_GT,V_I,a,(intptr_t)(b),0,l)
#define v_bgtui(a,b,l)  v_emit_branch(V_X64_GT,V_U,a,(intptr_t)(b),0,l)
#define v_bgtli(a,b,l)  v_emit_branch(V_X64_GT,V_L,a,(intptr_t)(b),0,l)
#define v_bgtuli(a,b,l) v_emit_branch(V_X64_GT,V_UL,a,(intptr_t)(b),0,l)
#define v_bgtpi(a,b,l)  v_emit_branch(V_X64_GT,V_P,a,(intptr_t)(b),0,l)
#define v_bgei(a,b,l)   v_emit_branch(V_X64_GE,V_I,a,b,1,l)
#define v_bgeu(a,b,l)   v_emit_branch(V_X64_GE,V_U,a,b,1,l)
#define v_bgel(a,b,l)   v_emit_branch(V_X64_GE,V_L,a,b,1,l)
#define v_bgeul(a,b,l)  v_emit_branch(V_X64_GE,V_UL,a,b,1,l)
#define v_bgep(a,b,l)   v_emit_branch(V_X64_GE,V_P,a,b,1,l)
#define v_bgeii(a,b,l)  v_emit_branch(V_X64_GE,V_I,a,(intptr_t)(b),0,l)
#define v_bgeui(a,b,l)  v_emit_branch(V_X64_GE,V_U,a,(intptr_t)(b),0,l)
#define v_bgeli(a,b,l)  v_emit_branch(V_X64_GE,V_L,a,(intptr_t)(b),0,l)
#define v_bgeuli(a,b,l) v_emit_branch(V_X64_GE,V_UL,a,(intptr_t)(b),0,l)
#define v_bgepi(a,b,l)  v_emit_branch(V_X64_GE,V_P,a,(intptr_t)(b),0,l)
#define v_beqi(a,b,l)   v_emit_branch(V_X64_EQ,V_I,a,b,1,l)
#define v_bequ(a,b,l)   v_emit_branch(V_X64_EQ,V_U,a,b,1,l)
#define v_beql(a,b,l)   v_emit_branch(V_X64_EQ,V_L,a,b,1,l)
#define v_bequl(a,b,l)  v_emit_branch(V_X64_EQ,V_UL,a,b,1,l)
#define v_beqp(a,b,l)   v_emit_branch(V_X64_EQ,V_P,a,b,1,l)
#define v_beqii(a,b,l)  v_emit_branch(V_X64_EQ,V_I,a,(intptr_t)(b),0,l)
#define v_bequi(a,b,l)  v_emit_branch(V_X64_EQ,V_U,a,(intptr_t)(b),0,l)
#define v_beqli(a,b,l)  v_emit_branch(V_X64_EQ,V_L,a,(intptr_t)(b),0,l)
#define v_bequli(a,b,l) v_emit_branch(V_X64_EQ,V_UL,a,(intptr_t)(b),0,l)
#define v_beqpi(a,b,l)  v_emit_branch(V_X64_EQ,V_P,a,(intptr_t)(b),0,l)
#define v_bnei(a,b,l)   v_emit_branch(V_X64_NE,V_I,a,b,1,l)
#define v_bneu(a,b,l)   v_emit_branch(V_X64_NE,V_U,a,b,1,l)
#define v_bnel(a,b,l)   v_emit_branch(V_X64_NE,V_L,a,b,1,l)
#define v_bneul(a,b,l)  v_emit_branch(V_X64_NE,V_UL,a,b,1,l)
#define v_bnep(a,b,l)   v_emit_branch(V_X64_NE,V_P,a,b,1,l)
#define v_bneii(a,b,l)  v_emit_branch(V_X64_NE,V_I,a,(intptr_t)(b),0,l)
#define v_bneui(a,b,l)  v_emit_branch(V_X64_NE,V_U,a,(intptr_t)(b),0,l)
#define v_bneli(a,b,l)  v_emit_branch(V_X64_NE,V_L,a,(intptr_t)(b),0,l)
#define v_bneuli(a,b,l) v_emit_branch(V_X64_NE,V_UL,a,(intptr_t)(b),0,l)
#define v_bnepi(a,b,l)  v_emit_branch(V_X64_NE,V_P,a,(intptr_t)(b),0,l)
#define v_bltf(a,b,l)   v_emit_branch(V_X64_LT,V_F,a,b,1,l)
#define v_bled(a,b,l)   v_emit_branch(V_X64_LE,V_D,a,b,1,l)
#define v_blef(a,b,l)   v_emit_branch(V_X64_LE,V_F,a,b,1,l)
#define v_bltd(a,b,l)   v_emit_branch(V_X64_LT,V_D,a,b,1,l)
#define v_bgtf(a,b,l)   v_emit_branch(V_X64_GT,V_F,a,b,1,l)
#define v_bgtd(a,b,l)   v_emit_branch(V_X64_GT,V_D,a,b,1,l)
#define v_bgef(a,b,l)   v_emit_branch(V_X64_GE,V_F,a,b,1,l)
#define v_bged(a,b,l)   v_emit_branch(V_X64_GE,V_D,a,b,1,l)
#define v_beqf(a,b,l)   v_emit_branch(V_X64_EQ,V_F,a,b,1,l)
#define v_beqd(a,b,l)   v_emit_branch(V_X64_EQ,V_D,a,b,1,l)
#define v_bnef(a,b,l)   v_emit_branch(V_X64_NE,V_F,a,b,1,l)
#define v_bned(a,b,l)   v_emit_branch(V_X64_NE,V_D,a,b,1,l)

#define v_ldi(d,b,o)   v_emit_load(V_I,d,b,(intptr_t)(o),1)
#define v_ldu(d,b,o)   v_emit_load(V_U,d,b,(intptr_t)(o),1)
#define v_ldl(d,b,o)   v_emit_load(V_L,d,b,(intptr_t)(o),1)
#define v_ldul(d,b,o)  v_emit_load(V_UL,d,b,(intptr_t)(o),1)
#define v_ldp(d,b,o)   v_emit_load(V_P,d,b,(intptr_t)(o),1)
#define v_lds(d,b,o)   v_emit_load(V_S,d,b,(intptr_t)(o),1)
#define v_ldus(d,b,o)  v_emit_load(V_US,d,b,(intptr_t)(o),1)
#define v_ldc(d,b,o)   v_emit_load(V_C,d,b,(intptr_t)(o),1)
#define v_lduc(d,b,o)  v_emit_load(V_UC,d,b,(intptr_t)(o),1)
#define v_ldii(d,b,o)  v_emit_load(V_I,d,b,(intptr_t)(o),0)
#define v_ldui(d,b,o)  v_emit_load(V_U,d,b,(intptr_t)(o),0)
#define v_ldli(d,b,o)  v_emit_load(V_L,d,b,(intptr_t)(o),0)
#define v_lduli(d,b,o) v_emit_load(V_UL,d,b,(intptr_t)(o),0)
#define v_ldpi(d,b,o)  v_emit_load(V_P,d,b,(intptr_t)(o),0)
#define v_ldsi(d,b,o)  v_emit_load(V_S,d,b,(intptr_t)(o),0)
#define v_ldusi(d,b,o) v_emit_load(V_US,d,b,(intptr_t)(o),0)
#define v_ldci(d,b,o)  v_emit_load(V_C,d,b,(intptr_t)(o),0)
#define v_lduci(d,b,o) v_emit_load(V_UC,d,b,(intptr_t)(o),0)
#define v_ldf(d,b,o)   v_emit_load(V_F,d,b,(intptr_t)(o),1)
#define v_ldd(d,b,o)   v_emit_load(V_D,d,b,(intptr_t)(o),1)
#define v_ldfi(d,b,o)  v_emit_load(V_F,d,b,(intptr_t)(o),0)
#define v_lddi(d,b,o)  v_emit_load(V_D,d,b,(intptr_t)(o),0)
#define v_alduci(d,b,o,a) v_lduci(d,b,o)
#define v_aldusi(d,b,o,a) v_ldusi(d,b,o)
#define v_aldui(d,b,o,a)  v_ldui(d,b,o)

#define v_sti(v,b,o)   v_emit_store(V_I,v,b,(intptr_t)(o),1)
#define v_stu(v,b,o)   v_emit_store(V_U,v,b,(intptr_t)(o),1)
#define v_stl(v,b,o)   v_emit_store(V_L,v,b,(intptr_t)(o),1)
#define v_stul(v,b,o)  v_emit_store(V_UL,v,b,(intptr_t)(o),1)
#define v_stp(v,b,o)   v_emit_store(V_P,v,b,(intptr_t)(o),1)
#define v_sts(v,b,o)   v_emit_store(V_S,v,b,(intptr_t)(o),1)
#define v_stus(v,b,o)  v_emit_store(V_US,v,b,(intptr_t)(o),1)
#define v_stc(v,b,o)   v_emit_store(V_C,v,b,(intptr_t)(o),1)
#define v_stuc(v,b,o)  v_emit_store(V_UC,v,b,(intptr_t)(o),1)
#define v_stii(v,b,o)  v_emit_store(V_I,v,b,(intptr_t)(o),0)
#define v_stui(v,b,o)  v_emit_store(V_U,v,b,(intptr_t)(o),0)
#define v_stli(v,b,o)  v_emit_store(V_L,v,b,(intptr_t)(o),0)
#define v_stuli(v,b,o) v_emit_store(V_UL,v,b,(intptr_t)(o),0)
#define v_stpi(v,b,o)  v_emit_store(V_P,v,b,(intptr_t)(o),0)
#define v_stsi(v,b,o)  v_emit_store(V_S,v,b,(intptr_t)(o),0)
#define v_stusi(v,b,o) v_emit_store(V_US,v,b,(intptr_t)(o),0)
#define v_stci(v,b,o)  v_emit_store(V_C,v,b,(intptr_t)(o),0)
#define v_stuci(v,b,o) v_emit_store(V_UC,v,b,(intptr_t)(o),0)
#define v_stf(v,b,o)   v_emit_store(V_F,v,b,(intptr_t)(o),1)
#define v_std(v,b,o)   v_emit_store(V_D,v,b,(intptr_t)(o),1)
#define v_stfi(v,b,o)  v_emit_store(V_F,v,b,(intptr_t)(o),0)
#define v_stdi(v,b,o)  v_emit_store(V_D,v,b,(intptr_t)(o),0)

#define v_jv(label) v_dmark((v_code *)(v_ip + 1),label),v_emit_byte(0xe9),v_emit_u32(0)
#define v_jp(reg) v_emit_jump_reg(reg)
#define v_jpi(address) v_emit_jump_imm((uintptr_t)(address))
#define v_jalv(label) v_dmark((v_code *)(v_ip + 1),label),v_emit_byte(0xe8),v_emit_u32(0)
#define v_jalp(reg) v_emit_call_reg(reg)
#define v_jalpi(address) v_emit_call_imm((uintptr_t)(address))

#define v_retv() v_emit_return(V_V,0,0,0)
#define v_reti(r) v_emit_return(V_I,r,0,0)
#define v_retu(r) v_emit_return(V_U,r,0,0)
#define v_retl(r) v_emit_return(V_L,r,0,0)
#define v_retul(r) v_emit_return(V_UL,r,0,0)
#define v_retp(r) v_emit_return(V_P,r,0,0)
#define v_retf(r) v_emit_return(V_F,r,0,0)
#define v_retd(r) v_emit_return(V_D,r,0,0)
#define v_retii(i) v_emit_return(V_I,0,(uintptr_t)(intptr_t)(i),1)
#define v_retui(i) v_emit_return(V_U,0,(uintptr_t)(i),1)
#define v_retli(i) v_emit_return(V_L,0,(uintptr_t)(intptr_t)(i),1)
#define v_retuli(i) v_emit_return(V_UL,0,(uintptr_t)(i),1)
#define v_retpi(i) v_emit_return(V_P,0,(uintptr_t)(i),1)

#define v_push_argi(c,r)  push_arg_reg(c,V_I,r)
#define v_push_argu(c,r)  push_arg_reg(c,V_U,r)
#define v_push_argl(c,r)  push_arg_reg(c,V_L,r)
#define v_push_argul(c,r) push_arg_reg(c,V_UL,r)
#define v_push_argp(c,r)  push_arg_reg(c,V_P,r)
#define v_push_argii(c,i)  push_arg_imm(c,V_I,(uintptr_t)(intptr_t)(i))
#define v_push_argui(c,i)  push_arg_imm(c,V_U,(uintptr_t)(i))
#define v_push_argli(c,i)  push_arg_imm(c,V_L,(uintptr_t)(intptr_t)(i))
#define v_push_arguli(c,i) push_arg_imm(c,V_UL,(uintptr_t)(i))
#define v_push_argpi(c,i)  push_arg_imm(c,V_P,(uintptr_t)(i))

#define v_nop() v_emit_nop()
#define v_nuke_nop() ((void)0)
#define v_schedule_delay(branch,delay) do { delay; branch; } while (0)
#define v_raw_load(mem,count) (mem)
#define v_flushcache(begin,end) ((void)0)

#define v_cvc2i(d,s)   v_emit_convert(V_I,V_C,d,s)
#define v_cvc2u(d,s)   v_emit_convert(V_U,V_C,d,s)
#define v_cvc2l(d,s)   v_emit_convert(V_L,V_C,d,s)
#define v_cvc2ul(d,s)  v_emit_convert(V_UL,V_C,d,s)
#define v_cvuc2i(d,s)  v_emit_convert(V_I,V_UC,d,s)
#define v_cvuc2u(d,s)  v_emit_convert(V_U,V_UC,d,s)
#define v_cvuc2l(d,s)  v_emit_convert(V_L,V_UC,d,s)
#define v_cvuc2ul(d,s) v_emit_convert(V_UL,V_UC,d,s)
#define v_cvs2i(d,s)   v_emit_convert(V_I,V_S,d,s)
#define v_cvs2u(d,s)   v_emit_convert(V_U,V_S,d,s)
#define v_cvs2l(d,s)   v_emit_convert(V_L,V_S,d,s)
#define v_cvs2ul(d,s)  v_emit_convert(V_UL,V_S,d,s)
#define v_cvus2i(d,s)  v_emit_convert(V_I,V_US,d,s)
#define v_cvus2u(d,s)  v_emit_convert(V_U,V_US,d,s)
#define v_cvus2l(d,s)  v_emit_convert(V_L,V_US,d,s)
#define v_cvus2ul(d,s) v_emit_convert(V_UL,V_US,d,s)
#define v_cvi2c(d,s)   v_emit_convert(V_C,V_I,d,s)
#define v_cvi2uc(d,s)  v_emit_convert(V_UC,V_I,d,s)
#define v_cvi2s(d,s)   v_emit_convert(V_S,V_I,d,s)
#define v_cvi2us(d,s)  v_emit_convert(V_US,V_I,d,s)
#define v_cvi2i(d,s)   v_emit_convert(V_I,V_I,d,s)
#define v_cvi2u(d,s)   v_emit_convert(V_U,V_I,d,s)
#define v_cvi2l(d,s)   v_emit_convert(V_L,V_I,d,s)
#define v_cvi2ul(d,s)  v_emit_convert(V_UL,V_I,d,s)
#define v_cvu2c(d,s)   v_emit_convert(V_C,V_U,d,s)
#define v_cvu2uc(d,s)  v_emit_convert(V_UC,V_U,d,s)
#define v_cvu2s(d,s)   v_emit_convert(V_S,V_U,d,s)
#define v_cvu2us(d,s)  v_emit_convert(V_US,V_U,d,s)
#define v_cvu2i(d,s)   v_emit_convert(V_I,V_U,d,s)
#define v_cvu2u(d,s)   v_emit_convert(V_U,V_U,d,s)
#define v_cvu2l(d,s)   v_emit_convert(V_L,V_U,d,s)
#define v_cvu2ul(d,s)  v_emit_convert(V_UL,V_U,d,s)
#define v_cvl2c(d,s)   v_emit_convert(V_C,V_L,d,s)
#define v_cvl2uc(d,s)  v_emit_convert(V_UC,V_L,d,s)
#define v_cvl2s(d,s)   v_emit_convert(V_S,V_L,d,s)
#define v_cvl2us(d,s)  v_emit_convert(V_US,V_L,d,s)
#define v_cvl2i(d,s)   v_emit_convert(V_I,V_L,d,s)
#define v_cvl2u(d,s)   v_emit_convert(V_U,V_L,d,s)
#define v_cvl2l(d,s)   v_emit_convert(V_L,V_L,d,s)
#define v_cvl2ul(d,s)  v_emit_convert(V_UL,V_L,d,s)
#define v_cvul2c(d,s)  v_emit_convert(V_C,V_UL,d,s)
#define v_cvul2uc(d,s) v_emit_convert(V_UC,V_UL,d,s)
#define v_cvul2s(d,s)  v_emit_convert(V_S,V_UL,d,s)
#define v_cvul2us(d,s) v_emit_convert(V_US,V_UL,d,s)
#define v_cvul2i(d,s)  v_emit_convert(V_I,V_UL,d,s)
#define v_cvul2u(d,s)  v_emit_convert(V_U,V_UL,d,s)
#define v_cvul2l(d,s)  v_emit_convert(V_L,V_UL,d,s)
#define v_cvul2ul(d,s) v_emit_convert(V_UL,V_UL,d,s)
#define v_cvul2p(d,s)  v_emit_convert(V_P,V_UL,d,s)
#define v_cvu2p(d,s)   v_emit_convert(V_P,V_U,d,s)
#define v_cvp2u(d,s)   v_emit_convert(V_U,V_P,d,s)
#define v_cvp2ul(d,s)  v_emit_convert(V_UL,V_P,d,s)
#define v_cvi2f(d,s)   v_emit_convert(V_F,V_I,d,s)
#define v_cvi2d(d,s)   v_emit_convert(V_D,V_I,d,s)
#define v_cvl2f(d,s)   v_emit_convert(V_F,V_L,d,s)
#define v_cvl2d(d,s)   v_emit_convert(V_D,V_L,d,s)
#define v_cvf2i(d,s)   v_emit_convert(V_I,V_F,d,s)
#define v_cvd2i(d,s)   v_emit_convert(V_I,V_D,d,s)
#define v_cvf2l(d,s)   v_emit_convert(V_L,V_F,d,s)
#define v_cvd2l(d,s)   v_emit_convert(V_L,V_D,d,s)
#define v_cvf2d(d,s)   v_emit_convert(V_D,V_F,d,s)
#define v_cvd2f(d,s)   v_emit_convert(V_F,V_D,d,s)

#define v_cvc2ii(d,s)   v_seti(d,(int)(signed char)(s))
#define v_cvc2ui(d,s)   v_setu(d,(unsigned int)(signed char)(s))
#define v_cvc2li(d,s)   v_setl(d,(long)(signed char)(s))
#define v_cvc2uli(d,s)  v_setul(d,(unsigned long)(signed char)(s))
#define v_cvuc2ii(d,s)  v_seti(d,(int)(unsigned char)(s))
#define v_cvuc2ui(d,s)  v_setu(d,(unsigned int)(unsigned char)(s))
#define v_cvuc2li(d,s)  v_setl(d,(long)(unsigned char)(s))
#define v_cvuc2uli(d,s) v_setul(d,(unsigned long)(unsigned char)(s))
#define v_cvs2ii(d,s)   v_seti(d,(int)(short)(s))
#define v_cvs2ui(d,s)   v_setu(d,(unsigned int)(short)(s))
#define v_cvs2li(d,s)   v_setl(d,(long)(short)(s))
#define v_cvs2uli(d,s)  v_setul(d,(unsigned long)(short)(s))
#define v_cvus2ii(d,s)  v_seti(d,(int)(unsigned short)(s))
#define v_cvus2ui(d,s)  v_setu(d,(unsigned int)(unsigned short)(s))
#define v_cvus2li(d,s)  v_setl(d,(long)(unsigned short)(s))
#define v_cvus2uli(d,s) v_setul(d,(unsigned long)(unsigned short)(s))
#define v_cvi2ci(d,s)   v_setc(d,(signed char)(int)(s))
#define v_cvi2uci(d,s)  v_setuc(d,(unsigned char)(int)(s))
#define v_cvi2si(d,s)   v_sets(d,(short)(int)(s))
#define v_cvi2usi(d,s)  v_setus(d,(unsigned short)(int)(s))
#define v_cvi2ii(d,s)   v_seti(d,(int)(s))
#define v_cvi2ui(d,s)   v_setu(d,(unsigned int)(s))
#define v_cvi2li(d,s)   v_setl(d,(long)(int)(s))
#define v_cvi2uli(d,s)  v_setul(d,(unsigned long)(int)(s))
#define v_cvu2ci(d,s)   v_setc(d,(signed char)(unsigned int)(s))
#define v_cvu2uci(d,s)  v_setuc(d,(unsigned char)(unsigned int)(s))
#define v_cvu2si(d,s)   v_sets(d,(short)(unsigned int)(s))
#define v_cvu2usi(d,s)  v_setus(d,(unsigned short)(unsigned int)(s))
#define v_cvu2ii(d,s)   v_seti(d,(int)(unsigned int)(s))
#define v_cvu2ui(d,s)   v_setu(d,(unsigned int)(s))
#define v_cvu2li(d,s)   v_setl(d,(long)(unsigned int)(s))
#define v_cvu2uli(d,s)  v_setul(d,(unsigned long)(unsigned int)(s))
#define v_cvl2ci(d,s)   v_setc(d,(signed char)(long)(s))
#define v_cvl2uci(d,s)  v_setuc(d,(unsigned char)(long)(s))
#define v_cvl2si(d,s)   v_sets(d,(short)(long)(s))
#define v_cvl2usi(d,s)  v_setus(d,(unsigned short)(long)(s))
#define v_cvl2ii(d,s)   v_seti(d,(int)(long)(s))
#define v_cvl2ui(d,s)   v_setu(d,(unsigned int)(long)(s))
#define v_cvl2li(d,s)   v_setl(d,(long)(s))
#define v_cvl2uli(d,s)  v_setul(d,(unsigned long)(s))
#define v_cvul2ci(d,s)  v_setc(d,(signed char)(unsigned long)(s))
#define v_cvul2uci(d,s) v_setuc(d,(unsigned char)(unsigned long)(s))
#define v_cvul2si(d,s)  v_sets(d,(short)(unsigned long)(s))
#define v_cvul2usi(d,s) v_setus(d,(unsigned short)(unsigned long)(s))
#define v_cvul2ii(d,s)  v_seti(d,(int)(unsigned long)(s))
#define v_cvul2ui(d,s)  v_setu(d,(unsigned int)(unsigned long)(s))
#define v_cvul2li(d,s)  v_setl(d,(long)(unsigned long)(s))
#define v_cvul2uli(d,s) v_setul(d,(unsigned long)(s))
#define v_cvul2pi(d,s)  v_setp(d,(uintptr_t)(s))
#define v_cvu2pi(d,s)   v_setp(d,(uintptr_t)(unsigned int)(s))
#define v_cvp2ui(d,s)   v_setu(d,(unsigned int)(uintptr_t)(s))
#define v_cvp2uli(d,s)  v_setul(d,(uintptr_t)(s))

#endif
